# GitBook configuration for Bodega Frontend
root: ./README.md
summary: ./SUMMARY.md

# Optional: Add metadata, plugins, or customizations below as needed
# For example:
# title: Bodega Frontend Documentation
# plugins:
#   - search
#   - highlight
